# if you're sharing your code publicly.

development:
  secret_key_base: '9f23fbb52ebb2a3890577d24f99d8eba687b1657372afea7663ccdfccdc15231f15aa7d9d0de92aa5cddaab161d37506586a17f5ee33dda4bff90a0ec668435e'
  WEATHER_KEY : 'e8UA0ZuZYsAOnad8tAwvOvlGrEdSkNJ9' #FINAL, Breathe California's Accuweather Account
  GOOGLE_MAPS_KEY : '0'
  GOOGLE_CLIENT_ID : '1028916177031-ar7g447u6t811r8qpk585iovv0ctcm67.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET : 'Ay2UzpvVz6wHjeMwRgnZ6_6P'

test:
  secret_key_base: '12053d7fca8786e600f844d3343feb29b58cf9820f072478e6a54379ccff69d9cbb696ba472ba1c4ccf1543c0613347b3e30fb1096285e425066229f391fa618'
  WEATHER_KEY : 'e8UA0ZuZYsAOnad8tAwvOvlGrEdSkNJ9' #FINAL, Breathe Califronia's Accuweather Account
  GOOGLE_MAPS_KEY : '0'
  GOOGLE_CLIENT_ID : '1028916177031-ar7g447u6t811r8qpk585iovv0ctcm67.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET : 'Ay2UzpvVz6wHjeMwRgnZ6_6P'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ACCUWEATHER_KEY : <%= ENV["WEATHER_KEY"] %>
  GOOGLE_MAPS_KEY : <%= ENV["GOOGLE_MAPS_KEY"] %>
  GOOGLE_CLIENT_ID : <%= ENV["GOOGLE_CLIENT_ID"] %>
  GOOGLE_CLIENT_SECRET : <%= ENV["GOOGLE_CLIENT_SECRET"] %>